# Generated by Django 6.0.4 on 2026-05-02 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian number like +919876543210', regex='^\\d{10}$')]),
        ),
    ]
